In [1]:
import numpy as np
import pandas as pd

模型本意在于使用随机森林模型填补颜色中的缺失值

In [2]:
train_data = pd.read_csv("relic_classify.csv")


In [3]:
test_data = pd.DataFrame([train_data.iloc[18,],train_data.iloc[39,],train_data.iloc[47,],train_data.iloc[57,]])
#18,39,47,57是缺失数据
train_data.dropna(inplace=True)#处理集合
test_data.dropna(axis=1,inplace=True)

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import *
from sklearn.metrics import *

In [4]:
y = pd.get_dummies(train_data["颜色"])
features = ["纹饰","类型","表面风化"]
X = pd.get_dummies(train_data[features])


In [20]:
model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=1,oob_score=True)
model.fit(X, y)

RandomForestClassifier(max_depth=10, oob_score=True, random_state=1)

In [21]:
print(model.feature_importances_)
print(model.oob_score_)
#print(cross_validation.cross_val_score(model,X,y,cv=5))

[0.13394894 0.12461026 0.23454014 0.18031237 0.16421279 0.08532464
 0.07705086]
0.46296296296296297


In [8]:
x_test = [[1,0,0,1,0,0,1],
          [0,0,1,1,0,0,1],
          [1,0,0,1,0,0,1],
          [0,0,1,1,0,0,1]]

In [10]:
predictions = model.predict(x_test)
print(predictions)

[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


c:\Users\Nucleon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


可见,模型填补效果并不好.二四两行颜色无法有效判别.经考虑并结合数据集发现,很有可能是文物表面风化严重导致颜色完全无法辨识导致的缺失值.在这里不能用一般的方法进行填补.故在数据处理上,表单一中的缺失颜色置为"无法识别"